import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.on('framenavigated', (f) => console.log('NAV:', f.url()));
page.on('console', (m) => console.log('CONSOLE', m.type(), m.text()));
page.on('pageerror', (e) => console.log('PAGEERROR', e.message));
await page.goto('http://localhost:5199/communaute/', { waitUntil: 'load', timeout: 20000 });
await page.waitForTimeout(3000);
console.log('URL now:', page.url());
await browser.close();
