import { chromium } from 'playwright';
const url = process.argv[2], out = process.argv[3], w = +process.argv[4], h = +process.argv[5];
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: w, height: h } });
await p.goto(url, { waitUntil: 'networkidle', timeout: 60000 });
await p.waitForTimeout(2500);
const txt = await p.evaluate(() => document.body.innerText);
console.log('---TEXTE---');
console.log(txt.split('\n').filter(l => /novembre|janvier|cohorte|November|January/i.test(l)).join('\n') || '(aucune ligne de date trouvée)');
await p.screenshot({ path: out, fullPage: false });
await b.close();
