import { chromium } from 'playwright';
const [,, base = 'http://localhost:5199', tag = 'or'] = process.argv;
const b = await chromium.launch();
const c = await b.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 });
await c.addInitScript(() => { try { localStorage.setItem('krystine-lang', 'fr'); } catch {} });
const p = await c.newPage();
await p.goto(base + '/medias', { waitUntil: 'load' });
await p.waitForTimeout(3000);
const accepte = p.locator('button:has-text("J\'accepte")').first(); if (await accepte.count()) { await accepte.click({ timeout: 2000 }).catch(() => {}); }
await p.evaluate(async () => { const pas = window.innerHeight * 0.7; for (let y = 0; y < document.body.scrollHeight; y += pas) { window.scrollTo(0, y); await new Promise(r => setTimeout(r, 120)); } });
const el = p.locator('a.cv-foil').first();
await el.scrollIntoViewIfNeeded(); await p.waitForTimeout(1000);
const r = await el.boundingBox();
const clip = { x: Math.max(0, r.x - 30), y: Math.max(0, r.y - 30), width: r.width + 60, height: r.height + 60 };
await p.screenshot({ path: `/tmp/lives-verif/collant-${tag}-repos.png`, clip });
await p.mouse.move(r.x + r.width * 0.25, r.y + r.height * 0.4); await p.waitForTimeout(500);
await p.screenshot({ path: `/tmp/lives-verif/collant-${tag}-survol-gauche.png`, clip });
await p.mouse.move(r.x + r.width * 0.8, r.y + r.height * 0.7); await p.waitForTimeout(500);
await p.screenshot({ path: `/tmp/lives-verif/collant-${tag}-survol-droite.png`, clip });
await p.screenshot({ path: `/tmp/lives-verif/footer-${tag}.jpg`, quality: 75 });
console.log('ok', JSON.stringify(r));
await b.close();
