import { chromium } from 'playwright';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 });
const p = await ctx.newPage();
await p.goto('http://localhost:5199/admin/habitudes', { waitUntil: 'domcontentloaded' });
await p.locator('button:has-text("Email")').click();
await p.fill('input[type="email"]', 'houseoftherisingarts@gmail.com');
await p.fill('input[type="password"]', 'EssaiHabitudes2026!');
await p.click('button[type="submit"]');
await p.waitForSelector('text=comptes au total', { timeout: 20000 });
await p.goto('http://localhost:5199/foyer-essai', { waitUntil: 'domcontentloaded' });
await p.waitForTimeout(2000);
await p.screenshot({ path: '/tmp/foyer-viewport-1.png' });
await p.mouse.wheel(0, 900);
await p.waitForTimeout(500);
await p.screenshot({ path: '/tmp/foyer-viewport-2.png' });
await b.close();
