import { chromium } from 'playwright';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 } });
const p = await ctx.newPage();
await p.goto('http://localhost:5199/admin/habitudes', { waitUntil: 'domcontentloaded' });
await p.waitForTimeout(2000);
const btn = p.locator('button:has-text("Email")');
console.log('count', await btn.count());
await btn.click();
await p.waitForTimeout(500);
console.log('inputs', await p.locator('input').count());
const email = p.locator('input[type="email"]');
console.log('email count', await email.count());
await email.fill('houseoftherisingarts@gmail.com');
await p.fill('input[type="password"]', 'EssaiHabitudes2026!');
await p.click('button[type="submit"]');
await p.waitForTimeout(4000);
console.log('BODY', (await p.locator('body').innerText()).slice(0, 800));
await p.screenshot({ path: '/tmp/debug2.png', fullPage: true });
await b.close();
