import { chromium } from 'playwright';
import fs from 'node:fs';
const BASE = 'http://localhost:5198';
const EMAIL = 'admin@krystinestlaurent.ca';
const PASSWORD = fs.readFileSync('/Users/lesalondesinconnus/.claude/scripts/.krystine_admin_pw', 'utf8').trim();
const OUT = 'scripts/qa/shots/detail-compteurs';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 });
const page = await ctx.newPage();
await page.goto(`${BASE}/admin`, { waitUntil: 'domcontentloaded' });
await page.waitForSelector('text=Accès Admin', { timeout: 15000 });
await page.click('button:has-text("Email")');
await page.fill('input[type="email"]', EMAIL);
await page.fill('input[type="password"]', PASSWORD);
await page.click('button:has-text("Se connecter")');
await page.waitForSelector('text=Votre communauté', { timeout: 20000 });
await page.waitForTimeout(1000);
await page.locator('p:has-text("Actives")').first().click();
await page.waitForSelector('h3:has-text("Actives")', { timeout: 10000 });
await page.waitForTimeout(2000);
await page.selectOption('select[title="Regrouper par"]', 'langue');
await page.waitForTimeout(500);
// Replie le premier groupe (Inconnu) — scopé au panneau (portail en fin de body)
await page.locator('.z-\\[130\\] button[aria-expanded="true"]').first().click();
await page.waitForTimeout(400);
await page.screenshot({ path: `${OUT}/9-groupe-replie-1440.jpg`, quality: 80 });
await b.close();
console.log('ok');
