import { chromium } from 'playwright';
const b = await chromium.launch();
const page = await b.newPage({ viewport: { width: 1440, height: 900 } });
const errs = [];
page.on('console', m => { if (m.type() === 'error') errs.push(m.text()); });
page.on('pageerror', e => errs.push('pageerror: ' + e.message));
page.on('requestfailed', r => errs.push('requestfailed: ' + r.url() + ' ' + (r.failure()?.errorText||'')));
await page.goto('https://www.krystinestlaurent.ca/medias', { waitUntil: 'networkidle', timeout: 30000 });
await page.waitForTimeout(2000);
console.log('=== erreurs ===');
errs.slice(0,25).forEach(e => console.log(e));
const html = await page.content();
console.log('=== longueur HTML ===', html.length);
console.log('=== extrait du body ===');
console.log(html.slice(html.indexOf('<body'), html.indexOf('<body')+1500));
await b.close();
