import { chromium } from 'playwright';
import { execSync } from 'node:child_process';
import fs from 'node:fs';
const API_KEY = fs.readFileSync('.env.local', 'utf8').match(/VITE_FIREBASE_API_KEY=(.+)/)[1].trim();
const PROJET = 'krystinestlaurent-87566'; const BASE = 'http://localhost:5199';
const OUT = '/private/tmp/claude-501/-Users-lesalondesinconnus/3a548c8f-1fba-4e35-b513-f459846a1c9b/scratchpad/sig';
const email = `qa-${Date.now()}@vexel-qa.test`; const password = 'Qa!' + Math.random().toString(36).slice(2, 12);
const rest = async (url, body) => (await fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) })).json();
const gtoken = execSync('gcloud auth print-access-token').toString().trim();
const fsdoc = async (path, fields) => fetch(`https://firestore.googleapis.com/v1/projects/${PROJET}/databases/(default)/documents/${path}`, { method: 'PATCH', headers: { Authorization: `Bearer ${gtoken}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ fields }) });
const fsdel = async (path) => fetch(`https://firestore.googleapis.com/v1/projects/${PROJET}/databases/(default)/documents/${path}`, { method: 'DELETE', headers: { Authorization: `Bearer ${gtoken}` } });
const u = await rest(`https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=${API_KEY}`, { email, password, returnSecureToken: true });
const uid = u.localId; const now = { timestampValue: new Date().toISOString() };
await fsdoc(`members/${uid}`, { uid: { stringValue: uid }, email: { stringValue: email }, displayName: { stringValue: 'Test QA' }, personnalisation: { mapValue: { fields: { banniere: { stringValue: 'iris' } } } } });
await fsdoc(`pointsEvents/adjust:${uid}:qa`, { uid: { stringValue: uid }, kind: { stringValue: 'adjust' }, amount: { integerValue: '300' }, dedupKey: { stringValue: `adjust:${uid}:qa` }, at: now });
await fsdoc(`memberPoints/${uid}`, { balance: { integerValue: '300' }, lifetime: { integerValue: '300' } });
await fsdoc(`boutique/${uid}`, { possede: { mapValue: { fields: { 'banniere-iris': now } } } });
const authUser = { uid, email, emailVerified: false, isAnonymous: false, displayName: 'Test QA', providerData: [{ providerId: 'password', uid: email, displayName: null, email, phoneNumber: null, photoURL: null }], stsTokenManager: { refreshToken: u.refreshToken, accessToken: u.idToken, expirationTime: Date.now() + Number(u.expiresIn) * 1000 }, createdAt: String(Date.now()), lastLoginAt: String(Date.now()), apiKey: API_KEY, appName: '[DEFAULT]' };
const browser = await chromium.launch(); const page = await (await browser.newContext({ viewport: { width: 1440, height: 900 } })).newPage();
await page.goto(`${BASE}/robots.txt`);
await page.evaluate(([key, val]) => new Promise((res, rej) => { localStorage.setItem('krystine-jeu-vu', new Date().toISOString().slice(0, 10)); localStorage.setItem('krystine-banniere-flash-vu', '1'); const req = indexedDB.open('firebaseLocalStorageDb', 1); req.onupgradeneeded = () => req.result.createObjectStore('firebaseLocalStorage', { keyPath: 'fbase_key' }); req.onsuccess = () => { const tx = req.result.transaction('firebaseLocalStorage', 'readwrite'); tx.objectStore('firebaseLocalStorage').put({ fbase_key: key, value: val }); tx.oncomplete = () => res(true); tx.onerror = rej; }; req.onerror = rej; }), [`firebase:authUser:${API_KEY}:[DEFAULT]`, authUser]);
const fermerRoue = async () => { const r = page.locator('.fixed.inset-0.z-\\[125\\]'); if (await r.count()) { await r.first().click({ position: { x: 8, y: 8 } }); await page.waitForTimeout(400); } };
try {
  await page.goto(`${BASE}/compte`, { waitUntil: 'domcontentloaded' }); await page.waitForSelector('#boutique, [class*="h-80"] img', { timeout: 20000 }).catch(() => {}); await page.waitForTimeout(2500); await fermerRoue();
  await page.screenshot({ path: `${OUT}/v2-01-hero-signature.png` });
  await page.goto(`${BASE}/compte?onglet=telechargements`, { waitUntil: 'domcontentloaded' }); await page.waitForSelector('#boutique-banniere', { timeout: 20000 }); await page.waitForTimeout(1500); await fermerRoue();
  await page.locator('#boutique-banniere').scrollIntoViewIfNeeded(); await page.waitForTimeout(500);
  await page.screenshot({ path: `${OUT}/v2-02-bannieres.png` });
  await page.evaluate(() => window.dispatchEvent(new Event('krystine:ouvrir-paquets'))); await page.waitForTimeout(1200);
  await page.screenshot({ path: `${OUT}/v2-03-paquets.png` });
  const sante = page.locator('text=Santé la vie').first(); await sante.scrollIntoViewIfNeeded(); await page.waitForTimeout(500);
  await page.screenshot({ path: `${OUT}/v2-04-sante-saisons.png` });
  const videos = page.locator('#videos-krystine'); await videos.scrollIntoViewIfNeeded(); await page.waitForTimeout(500);
  await page.screenshot({ path: `${OUT}/v2-05-videos.png` });
  const boxSante = await sante.boundingBox(); const boxVideos = await videos.boundingBox();
  console.log('ordre : Santé y=', Math.round(boxSante?.y ?? -1), 'vidéos y=', Math.round(boxVideos?.y ?? -1), '(vidéos doivent être plus bas dans la page : comparer via scrollY)');
} finally { await browser.close(); await rest(`https://identitytoolkit.googleapis.com/v1/accounts:delete?key=${API_KEY}`, { idToken: u.idToken }); for (const p of [`members/${uid}`, `memberPoints/${uid}`, `boutique/${uid}`, `pointsEvents/adjust:${uid}:qa`]) await fsdel(p); console.log('fini'); }
