import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await (await browser.newContext({ viewport: { width: 1280, height: 900 } })).newPage();
await page.goto('http://localhost:5199/', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(2500);
await page.screenshot({ path: '/private/tmp/claude-501/-Users-lesalondesinconnus/3a548c8f-1fba-4e35-b513-f459846a1c9b/scratchpad/revue/paquets-niskas/n5-debug-home.png' });
const buttons = await page.locator('button').allTextContents();
console.log('BUTTONS:', JSON.stringify(buttons.filter(t => t.trim())));
console.log('URL:', page.url());
await browser.close();
