import { chromium } from 'playwright';
import fs from 'node:fs';
const B='http://localhost:3021';
const pw = fs.readFileSync(`${process.env.HOME}/.claude/scripts/.krystine_admin_pw`,'utf8').trim();
const nav = await chromium.launch();
const ctx = await nav.newContext({ viewport:{width:1440,height:900} });
const page = await ctx.newPage();
page.on('console', m => console.log('  [console]', m.type(), m.text().slice(0,200)));
page.on('pageerror', e => console.log('  [pageerror]', String(e).slice(0,200)));
await page.goto(`${B}/compte`, { waitUntil:'domcontentloaded' });
await page.waitForTimeout(3000);
const boutons = await page.locator('button').allTextContents();
console.log('BOUTONS:', JSON.stringify(boutons.slice(0,20)));
await page.getByRole('button', { name:/se connecter|sign in/i }).first().click();
await page.waitForTimeout(1500);
console.log('email visible?', await page.locator('input[type="email"]').count());
await page.locator('input[type="email"]').first().fill('admin@krystinestlaurent.ca');
await page.locator('input[type="password"]').first().fill(pw);
await page.locator('form button[type="submit"]').first().click();
await page.waitForTimeout(7000);
console.log('URL:', page.url());
console.log('erreur modale:', await page.locator('p.text-red-500').allTextContents());
console.log('texte page:', (await page.locator('body').innerText()).slice(0,400).replace(/\n+/g,' | '));
await nav.close();
