import { chromium } from 'playwright';
const OUT = '/private/tmp/claude-501/-Users-lesalondesinconnus/cf4d63db-047d-4841-bf85-9cd29643fbb5/scratchpad';
const BASE='https://krystinestlaurent-87566--apercu-krystine-5ix7leua.web.app';
const b = await chromium.launch();
const errs=[];
const page = await (await b.newContext({ viewport:{width:1440,height:900} })).newPage();
page.on('pageerror',e=>errs.push('PE:'+e.message));
await page.goto(BASE+'/origine',{waitUntil:'load',timeout:40000}).catch(e=>errs.push('GOTO '+e.message));
await page.waitForTimeout(5000);
await page.screenshot({ path:`${OUT}/live2-origine.png` });
const info = await page.evaluate(()=>({nav:document.querySelectorAll('nav').length, h1:(document.querySelector('h1')||{}).innerText||'', hasEnvelope:!!document.querySelector('img[alt*="Enveloppe"]')}));
console.log(JSON.stringify(info));
console.log('PE='+errs.length+(errs.length?' | '+errs.slice(0,3).join(' | '):''));
await b.close();
