// ─── Shared Content for both Krystine & Inspirata ─────────────────────────────
// FR and EN only (Phase 1)

export const ASSETS = {
  logo: `https://storage.googleapis.com/inspirata/Vata/1%20(1).png`,
  navLogo: `https://storage.googleapis.com/inspirata/Vata/1%20(1).png`,
  // Original Inspirata gold logos kept for reference / backwards compat:
  logoInspirata: `https://storage.googleapis.com/inspirata/Base%20site/Golden%20drop%20inpirata.png`,
  navLogoInspirata: `https://storage.googleapis.com/inspirata/Base%20site/inspirata%20logo%202%20%20golden.png`,
  founder: `https://storage.googleapis.com/inspirata/Gemini_Generated_Image_99odj99odj99odj9.png`,
  founderHover: `https://storage.googleapis.com/inspirata/black%20on%20beige%20krystine.jpg`,
  shopBg: `https://storage.googleapis.com/inspirata/defripante_xmas.png`,
  ayurvedaBg: `https://storage.googleapis.com/inspirata/rituel%208.png`,
  blogBg: `https://storage.googleapis.com/inspirata/krystine%20podcast.png`,
  livresBg: `https://storage.googleapis.com/inspirata/Livres/nature%20ayurveda%20front.jpg`,
  formationsBg: `https://storage.googleapis.com/origine1/banner%20origine%20enveloppe.jpg`,
  evenementsBg: `https://storage.googleapis.com/origine1/krystine%20red%20NG.webp`,
  audio: `https://storage.googleapis.com/inspirata/Base%20site/homecoming-tranquilium-main-version-25793-03-28.mp3`,
  dropSound: 'https://assets.mixkit.co/active_storage/sfx/2571/2571-preview.m4a',
  productVata: 'https://storage.googleapis.com/inspirata/products/dosha-oils-group.webp',
  krystineRed: 'https://storage.googleapis.com/origine1/krystine%20red%20NG.webp',
  origineBanner: 'https://storage.googleapis.com/origine1/banner%20origine%20enveloppe.jpg',
  chakras: [
    'https://storage.googleapis.com/inspirata/Chakras/483-4834340_sahasrara-chakra-symbol-png-png-download-crown-chakra.png',
    'https://storage.googleapis.com/inspirata/Chakras/root-chakra-muladhara-of-golden-red-color-with-elegant-mandala-pattern-and-sanskrit-letters-in-the-center-energy-balance-hand-drawn-watercolor-illustration-ethnic-indian-pattern-png.png',
    'https://storage.googleapis.com/inspirata/Chakras/sacral-chakra-svadhisthana-of-golden-orange-color-with-elegant-mandala-pattern-and-sanskrit-letters-in-the-center-energy-balance-hand-drawn-watercolor-illustration-ethnic-indian-pattern-png.png',
    'https://storage.googleapis.com/inspirata/Chakras/solar-plexus-chakra-manipura-of-golden-yellow-color-with-elegant-mandala-pattern-and-sanskrit-letters-in-the-center-energy-balance-hand-drawn-watercolor-illustration-ethnic-indian-pattern-png.png',
    'https://storage.googleapis.com/inspirata/Chakras/third-eye-chakra-ajna-of-golden-dark-blue-color-with-elegant-mandala-pattern-and-sanskrit-letters-in-the-center-energy-balance-hand-drawn-watercolor-illustration-ethnic-indian-pattern-png.png',
  ],
};

export const CONTENT = {
  FR: {
    nav: {
      home: 'Accueil',
      krystine: 'Krystine',
      ayurveda: 'Ayurveda',
      formations: 'Formations & Événements',
      boutique: 'Boutique Inspirata Ayurveda',
      livres: 'Livres',
      medias: 'Podcasts, Médias & Livres',
      evenements: 'Événements',
      blogue: 'Blogue',
      pointsDeVente: 'Points de Vente',
      conferenciere: 'Conférencière',
      origine: 'Expérience Origine',
      podcast: 'Podcast',
      vata: 'Programme Vata',
      dimanchesOrigine: 'Dimanches d\'Origine',
      admin: 'Admin',
    },
    cards: {
      founder: { title: 'Krystine St-Laurent', subtitle: 'Découvrir', link: '/krystine', banner: '' },
      shop: { title: 'Boutique Inspirata Ayurveda', subtitle: 'Magasiner', link: '/boutique', locations: 'Points de Ventes', banner: 'Prendre soin' },
      ayurveda: { title: 'Ayurveda & Quiz Dosha', subtitle: 'Explorer', link: '/medias#ayurveda', banner: '' },
      livres: { title: 'Livres', subtitle: 'Lire', link: '/medias#livres', banner: '' },
      formations: { title: 'Formations & Événements', subtitle: 'Parcourir', link: '/formations', banner: 'Apprendre' },
      blog: { title: 'Podcasts, Médias & Livres', subtitle: 'Explorez nos contenus', link: '/medias', banner: 'Découvrir' },
      evenements: { title: 'Événements', subtitle: 'Rejoindre', link: '/formations#evenements', banner: '' },
    },
    gem: {
      placeholder: 'Dites-moi ce que vous cherchez...',
      button: 'Demander',
      thinking: 'Connexion...',
      modalTitle: 'Votre Guide Inspirata',
    },
    guideBtn: 'Laissez-vous guider',
    backToHome: 'Retour à l\'accueil',
    toggle: 'FR',
    ayurveda: {
      whatIsTitle: 'QU\'EST-CE QUE L\'AYURVEDA ?',
      whatIsText: 'Science sœur du Yoga, l\'Ayurveda est une sagesse ancestrale vieille de 5000 ans qui nous invite à reconnecter avec les rythmes de la nature. Elle ne traite pas seulement les symptômes, mais cherche à rétablir l\'harmonie unique entre le corps, l\'âme et l\'esprit.',
      title: 'Dosha Quiz',
      introTitle: 'INSPIRATA AYURVEDA',
      introText: 'Peut-être avez-vous toujours pensé que vous étiez unique… mais savez-vous à quel point ?',
      desc: 'L\'ayurveda considère que nous sommes constitués des cinq éléments – Espace, Air, Feu, Eau et Terre – et que leur combinaison donne naissance aux trois doshas : Vata (vent), Pitta (feu) et Kapha (eau).',
      quizPrompt: 'Complétez le quiz pour découvrir votre dominance actuelle.',
      quizBtn: 'Faire Le Quizz',
      resultsInfo: 'Selon votre résultat, découvrez les trucs de Krystine :',
      doshas: [
        { name: 'Vata', elements: 'Vent & Espace', action: 'Enraciner, réchauffer et apaiser', definition: 'Vata gouverne tout ce qui bouge. Il est sec, léger, froid, rugueux, subtil et mobile.', color: 'bg-gradient-to-br from-[#8F9779] to-[#4A5D23]', productRecom: 'Huile Corporelle Vata' },
        { name: 'Pitta', elements: 'Feu & Eau', action: 'Rafraîchir, apaiser et adoucir', definition: 'Pitta gouverne la digestion et le métabolisme. Il est chaud, tranchant, léger, liquide et huileux.', color: 'bg-gradient-to-br from-[#D98E73] to-[#BC4A3C]', productRecom: 'Huile Corporelle Pitta' },
        { name: 'Kapha', elements: 'Eau & Terre', action: 'Activer et stimuler', definition: 'Kapha gouverne la structure et la lubrification. Il est lourd, froid, lent, onctueux, doux et statique.', color: 'bg-gradient-to-br from-[#4A7C9D] to-[#2F4F4F]', productRecom: 'Huile Corporelle Kapha' },
      ],
      footer: 'Vous n\'avez pas reçu votre résultat ? Vérifiez votre boîte de courriel indésirable ou contactez : equipe@inspiratanature.com',
    },
    featured: {
      back: 'Retour',
      hero: { title: 'RAYONS DE SOLEIL LIQUIDE', subtitle: 'HUILES INFUSÉES DE PLANTES ENTIÈRES', cta: 'DÉCOUVREZ NOS HUILES' },
      intro: { title: 'HUILES CORPORELLES INFUSÉES DE PLANTES LOCALES', subtitle: 'Hydrate + Adoucit + Active', quote: 'Et que notre corps nous fait sentir qu\'il est temps d\'agir....' },
      title: 'Rituels du Moment',
      subtitle: 'Nos essentiels',
      products: [
        { name: 'Huile Corps Vata', price: '48.00 CAD', type: 'Ancrage & Sérénité' },
        { name: 'Rituel Visage', price: '85.00 CAD', type: 'Éclat Naturel' },
        { name: 'Livre: Nature & Ayurveda', price: '34.95 CAD', type: 'Sagesse Quotidienne' },
      ],
    },
    shop: {
      title: 'Boutique Inspirata Ayurveda',
      subtitle: 'Nature & Bien-être',
      products: [
        { id: 1, title: "L'Apaisante Vata", price: '48.00 CAD', type: 'Huile Corporelle', image: ASSETS.productVata },
        { id: 2, title: 'La Rafraîchissante Pitta', price: '48.00 CAD', type: 'Huile Corporelle', image: ASSETS.productVata },
        { id: 3, title: 'La Stimulante Kapha', price: '48.00 CAD', type: 'Huile Corporelle', image: ASSETS.productVata },
        { id: 4, title: 'Nez Zen', price: '28.00 CAD', type: 'Soins Spécifiques', image: ASSETS.productVata },
      ],
    },
    locations: {
      title: 'Nos précieux collaborateurs',
      intro: 'Chacun de nos partenaires a été choisi avec soin pour ses valeurs et sa connexion de cœur.',
      regions: [
        { name: 'Cantons de l\'Est', spots: [
          { name: 'Spa Eastman', address: '895 ch des Dilligences\nEastman, QC, J0E 1P0', tel: '1 800 665-5272', hours: 'Lundi au Dimanche : 7h00 à 22h00' },
          { name: 'Caroline Cazes', address: '1074 chemin de la Montagne\nOrford, QC, J1X 6X9', tel: '819-578-7707', hours: 'Sur rendez-vous seulement' },
        ]},
        { name: 'Québec - Trois Rivières', spots: [
          { name: 'Monastère des Augustines', address: '77 rue des Remparts\nQuébec, QC, G1R 0C3', tel: '418 694-1639', hours: 'Lundi au dimanche : 7 h à 21 h' },
          { name: 'Bloomi - Soins biologiques', address: '507 rue Saint-Joseph Est\nQuébec, QC, G1K 3B7', tel: '418 529-7470', hours: 'Lundi-Mercredi 10h-17h30\nJeudi-Vendredi 10h-20h\nSamedi 10h-17h' },
        ]},
        { name: 'Lanaudière', spots: [
          { name: 'Éco-Boutique Un monde à vie', address: '160 montée Masson\nMascouche, QC, J7K 3B5', tel: '450 474-5078', hours: 'Lundi-Vendredi 9h30-20h\nSamedi-Dimanche 9h30-17h' },
        ]},
        { name: 'Laurentides', spots: [
          { name: 'Librairie Quintessence', address: '275 rue Principale\nSaint-Sauveur, QC, J0R 1R0', tel: '450 227-5525', hours: 'Lundi-Mercredi 10h-18h\nJeudi-Samedi 10h-21h\nDimanche 10h-18h' },
        ]},
      ],
    },
    media: {
      title: 'Podcast & Médias',
      subtitle: 'Explorez nos contenus',
      back: 'Retour',
      sections: [
        { id: 'podcast', label: 'Podcast', icon: 'fa-microphone' },
        { id: 'tv', label: 'TV', icon: 'fa-tv' },
        { id: 'book', label: 'Livres', icon: 'fa-book' },
        { id: 'blog', label: 'Blog', icon: 'fa-pen-nib' },
      ],
      details: {
        podcast: {
          title: 'Au-delà des tendances',
          subtitle: 'Le Podcast Inspirata',
          spotifyUrl: 'https://open.spotify.com/embed/show/0cHEVMLF92tJxiO7MwyOKD?utm_source=generator',
          ctaLink: 'https://open.spotify.com/show/0cHEVMLF92tJxiO7MwyOKD',
          points: ['Conversations profondes, loin du bruit ambiant.', 'Clés pratiques inspirées de la sagesse vivante.', 'Une voix pour retrouver énergie et clarté.'],
          newsletter: { title: 'Restons connectés', subtitle: '( hors des réseaux sociaux )', desc: 'Recevez chaque nouvel épisode du podcast Inspirata directement par courriel.', button: "Je m'inscris" },
          cta: 'Accéder aux épisodes',
          promo: '🌿 Découvrir les Rituels Essentiels — APAISE, NOURRIT, TRANSFORME 27 $',
        },
        tv: {
          title: 'Émissions et Entrevues',
          desc: 'Notre fondatrice, à la barre de son émission SANTÉ LA VIE d\'une durée de 3 saisons, a été invitée sur plusieurs plateformes pour parler de l\'Ayurveda.',
          videos: [
            { id: 'v9uMfDmQ2YE', title: 'Santé! La Vie!' },
            { id: 'fxzVTt5RfBw', title: 'Salut Bonjour' },
            { id: '8t1BfEk_2do', title: 'François Lemay - Inspire toi' },
            { id: 'wtQ_MEgkrVE', title: 'Daniel Blouin' },
            { id: 'ab-EEYQi7yM', title: 'France Gauthier' },
            { id: 't3KNbXTyI5I', title: 'Diva Yoga - Entrevue' },
            { id: '2KWQuUbhmsU', title: 'Diva Yoga - Rituel' },
          ],
        },
        book: {
          title: 'Nos Livres',
          items: [
            {
              title: 'Nature & Ayurveda', fullTitle: 'Livre Nature & Ayurveda', subtitle: 'Best seller x 5 en francophonie',
              status: 'available', price: '34.99 CAD', reviews: '21 avis',
              cover: 'https://storage.googleapis.com/inspirata/Livres/nature%20ayurveda%20front.jpg',
              shortDesc: 'Si l\'Ayurveda était un livre, il se nommerait Nature & Ayurveda!\nProfesseurs de yoga, ceci est votre livre de référence!',
              features: ['Vegan', 'Ingrédients authentiques', 'Eco-responsable'],
              longDesc: 'Ce livre est bien plus qu\'un guide : c\'est un voyage vers l\'équilibre.\nIl aborde les fondements de l\'Ayurveda avec simplicité et profondeur.',
              conclusion: 'Nature & Ayurveda est le guide essentiel pour vivre une vie plus équilibrée.',
              detailedReviews: [
                { user: 'Marie-Claude', text: 'Une révélation! Ce livre a changé ma routine quotidienne.', rating: 5 },
                { user: 'Sophie L.', text: 'Le guide que j\'attendais. Simple, accessible et tellement beau.', rating: 5 },
                { user: 'Isabelle G.', text: 'Un bijou à offrir et à s\'offrir. Krystine transmet sa passion avec cœur.', rating: 5 },
              ],
            },
            {
              title: 'Féminité & Ayurveda', fullTitle: 'Livre Féminité & Ayurveda', subtitle: 'Best seller x 5 en francophonie',
              status: 'available', price: '39.99 CAD', reviews: '25 avis',
              cover: 'https://storage.googleapis.com/inspirata/Livres/feminite%20ayurveda%20front.jpg',
              shortDesc: 'Si l\'Ayurveda pouvait exprimer son lien avec le Féminin Sacré, il écrirait Féminité & Ayurveda.',
              features: ['Vegan', 'Soutien Hormonal', 'Bien-être Féminin'],
              longDesc: 'Une douce invitation à reconnecter avec votre corps, vos cycles et votre puissance intérieure.',
              conclusion: 'Féminité & Ayurveda est le compagnon idéal pour toute femme.',
              previewPages: [
                'https://storage.googleapis.com/inspirata/Livres/page%202%20fem.avif',
                'https://storage.googleapis.com/inspirata/Livres/page%202.avif',
              ],
              detailedReviews: [
                { user: 'Julie P.', text: 'Indispensable pour toutes les femmes. Une approche douce et bienveillante.', rating: 5 },
                { user: 'Chantal R.', text: 'Merci Krystine pour ce partage de sagesse. Je me sens enfin comprise.', rating: 5 },
                { user: 'Nathalie B.', text: 'Des rituels simples qui font une énorme différence sur mon bien-être.', rating: 5 },
              ],
            },
            { title: 'Sagesse à venir', desc: 'Prochainement', status: 'locked' },
          ],
        },
        blog: { title: 'Le Blogue', subtitle: 'Lectures et Réflexions' },
        default: { title: 'Bientôt', items: [] },
      },
    },
    founder: {
      bio: {
        intro: 'Dans un monde en accélération constante, il devient essentiel de ralentir. De revenir à ce qui soutient : le souffle, le corps, l\'énergie vivante.',
        p1: 'Depuis plus de 35 ans, je tisse des rituels enracinés dans l\'Ayurveda, les plantes, la respiration, et l\'écoute intérieure.',
        p2: 'Ce travail ne suit pas les tendances. Il s\'inscrit dans un art de vivre conscient.',
        highlight: 'Deux de mes livres ont été consacrés best-sellers.',
        expert: 'Infirmière d\'urgence (10 ans)',
        mission: 'Je consacre ma vie à l\'Art de vivre conscient.',
        outro: 'Bienvenue dans un espace pour reconnecter.',
      },
      stats: [
        { value: '35+', label: 'Années d\'Expérience', sub: 'Santé Holistique' },
        { value: '2', label: 'Francophonie', sub: 'Best-Sellers' },
        { value: '3', label: 'Santé La Vie', sub: 'Saisons TV' },
        { value: '10', label: 'Soins Critiques', sub: 'Années' },
      ],
      story: {
        title: 'L\'HISTOIRE D\'AMOUR',
        subtitle: 'ENTRE KRYSTINE ST-LAURENT & L\'AYURVEDA',
        p1: 'J\'ai l\'immense privilège de vivre au quotidien mon rêve de vie: me rebrancher à l\'abondance et la sagesse infinie que porte la nature.',
        p2: 'C\'est inspirée de l\'histoire des premières infirmières arrivées en Amérique (les sœurs Augustines).',
        p3: 'Je crois profondément que notre corps est unique et qu\'il est fait pour se régénérer.',
        p4: 'Imaginez une collectivité vibrante, vivante, consciente.',
        p5: 'Je souhaite vous accompagner dans ce chemin que propose l\'Ayurveda: un retour vers soi.',
      },
      newsletter: {
        title: 'Ce n\'est pas une infolettre.',
        subtitle: 'C\'est un fil de sagesse.',
        intro: 'Dans un monde qui change à chaque seconde… Ici, pas de tendance à suivre.',
        list: ['Parfois : une méditation, un rituel', 'Parfois : un extrait du prochain livre', 'Parfois : un simple rappel'],
        outro: 'Pour celles et ceux qui ressentent un appel — même doux, même flou.',
        formTitle: 'Rester connecté·e',
        cta: 'Rejoindre le fil',
      },
      footerBio: {
        title: 'QUI EST KRYSTINE ST-LAURENT?',
        text: 'Krystine St-Laurent est une autrice best-seller, conférencière internationale et experte reconnue en Ayurveda.',
      },
      cta: 'Réserver Krystine',
    },
    booking: {
      title: 'Réserver Krystine pour votre évènement!',
      bio: 'Krystine St-Laurent est une experte reconnue en Ayurveda, santé holistique et art de vivre aligné.',
      program: 'Formée à l\'international, autrice de livres à succès et conférencière recherchée.',
      ritual: {
        title: 'Si votre corps réécrivait l\'agenda de décembre?',
        desc: 'Rejoignez nous pour un 21 jours de rituels, simples, 5 à 10 minutes par jour!',
        cta: 'Je rejoins le mouvement',
        kajabiLink: 'https://kajabi.com/checkout-placeholder',
      },
    },
    evenements: {
      title: 'Événements',
      subtitle: 'Rencontrez Krystine en personne',
      noEvents: 'Aucun événement à venir pour l\'instant. Revenez bientôt!',
      register: 'S\'inscrire',
      inPerson: 'En personne',
      online: 'En ligne',
      past: 'Événements Passés',
      upcoming: 'À Venir',
    },
    footer: {
      contact: 'Contact',
      newsletter: 'Infolettre',
      privacy: 'Politique de confidentialité',
      madeBy: 'Plateforme développée par',
    },
    // Origine page content (from existing constants.ts)
    origine: {
      hero: {
        title: 'Expérience Origine',
        subtitle: 'Le problème n\'est pas un manque de discipline. C\'est la perte d\'un référentiel intérieur fiable.',
        cta: 'Rejoindre l\'Atelier',
      },
      transition: 'Découvrir encore plus avec Krystine',
      about: {
        title: 'Krystine St-Laurent',
        p1: '35 ans à traverser les milieux de la santé — soins intensifs, industrie pharmaceutique, recherche clinique en insuffisance cardiaque — avant de choisir l\'herboristerie, l\'Ayurveda et l\'aromathérapie.',
        testimonials: [
          { text: 'Personne ne parle de ces choses-là comme Krystine. Quand elle explique, tout devient clair.', author: 'Annie' },
          { text: 'Je me suis rarement écoutée tout au long de ma vie. C\'est la première fois que quelqu\'un me donne les outils pour le faire.', author: 'Françoise' },
          { text: 'Ce que j\'ai lu dans cent livres sans comprendre, Krystine l\'a rendu évident.', author: 'Marie' },
        ],
      },
      timeline: {
        title: 'Le Sentier de l\'Apothicaire',
        intro: 'Un parcours progressif en 3 temps pour rétablir votre boussole intérieure.',
        steps: [
          { id: '01', title: 'L\'Ancrage (Terre)', duration: 'Semaines 1-4', desc: 'Installer le repère.', details: 'Nous descendons dans la matière. Sommeil, alimentation, routines du matin.' },
          { id: '02', title: 'L\'Alchimie (Feu)', duration: 'Semaines 5-8', desc: 'La transformation digestive.', details: 'Le feu digestif (Agni) n\'est pas que dans l\'estomac.' },
          { id: '03', title: 'La Clarté (Éther)', duration: 'Semaines 9-12', desc: 'Incarner la cohérence.', details: 'Quand le bruit s\'apaise, la vision devient claire.' },
        ],
      },
      pricing: {
        title: 'Rejoignez le Cercle',
        price: 'Accès Fondateur',
        features: ['Accès complet aux 3 Modules', 'Workbooks (Grimoires) à imprimer', 'Sessions Q&A mensuelles', 'Communauté privée'],
        cta: 'Commencer l\'Expérience',
        guarantee: { badge: 'Garantie 30 Jours', title: 'Garantie Cœur Léger', text: 'Si vous ne ressentez pas l\'ancrage promis, nous vous remboursons intégralement.' },
      },
    },
  },
  EN: {
    nav: {
      home: 'Home',
      krystine: 'Krystine',
      ayurveda: 'Ayurveda',
      formations: 'Programs & Events',
      boutique: 'Inspirata Ayurveda Shop',
      livres: 'Books',
      medias: 'Podcasts, Media & Books',
      evenements: 'Events',
      blogue: 'Blog',
      pointsDeVente: 'Sales Points',
      conferenciere: 'Speaker',
      origine: 'Origin Experience',
      podcast: 'Podcast',
      vata: 'Vata Program',
      dimanchesOrigine: 'Sundays of Origin',
      admin: 'Admin',
    },
    cards: {
      founder: { title: 'Krystine St-Laurent', subtitle: 'Discover', link: '/krystine', banner: '' },
      shop: { title: 'Inspirata Ayurveda Shop', subtitle: 'Shop Now', link: '/boutique', locations: 'Sales Points', banner: 'Nurture' },
      ayurveda: { title: 'Ayurveda & Quiz Dosha', subtitle: 'Explore', link: '/medias#ayurveda', banner: '' },
      livres: { title: 'Books', subtitle: 'Read', link: '/medias#livres', banner: '' },
      formations: { title: 'Programs & Events', subtitle: 'Browse', link: '/formations', banner: 'Learn' },
      blog: { title: 'Podcasts, Media & Books', subtitle: 'Explore our content', link: '/medias', banner: 'Discover' },
      evenements: { title: 'Events', subtitle: 'Join us', link: '/formations#evenements', banner: '' },
    },
    gem: { placeholder: 'Tell me what you seek...', button: 'Ask', thinking: 'Connecting...', modalTitle: 'Your Inspirata Guide' },
    guideBtn: 'Let yourself be guided',
    backToHome: 'Back to Home',
    toggle: 'EN',
    ayurveda: {
      whatIsTitle: 'WHAT IS AYURVEDA?',
      whatIsText: 'Sister science of Yoga, Ayurveda is a 5000-year-old ancestral wisdom that invites us to reconnect with nature\'s rhythms.',
      title: 'Dosha Quiz',
      introTitle: 'INSPIRATA AYURVEDA',
      introText: 'Perhaps you\'ve always thought you were unique... but do you know to what extent?',
      desc: 'Ayurveda considers that we are made of five elements – Space, Air, Fire, Water and Earth.',
      quizPrompt: 'Take the quiz to discover your current dominance.',
      quizBtn: 'Take Quiz',
      resultsInfo: 'Based on your result, discover Krystine\'s tips:',
      doshas: [
        { name: 'Vata', elements: 'Wind & Space', action: 'Ground, warm and soothe', definition: 'Vata governs movement. It is dry, light, cold, rough, subtle and mobile.', color: 'bg-gradient-to-br from-[#8F9779] to-[#4A5D23]', productRecom: 'Vata Body Oil' },
        { name: 'Pitta', elements: 'Fire & Water', action: 'Cool, soothe and soften', definition: 'Pitta governs digestion and metabolism. It is hot, sharp, light, liquid and oily.', color: 'bg-gradient-to-br from-[#D98E73] to-[#BC4A3C]', productRecom: 'Pitta Body Oil' },
        { name: 'Kapha', elements: 'Water & Earth', action: 'Activate and stimulate', definition: 'Kapha governs structure and lubrication. It is heavy, cold, slow, unctuous, soft and static.', color: 'bg-gradient-to-br from-[#4A7C9D] to-[#2F4F4F]', productRecom: 'Kapha Body Oil' },
      ],
      footer: 'Haven\'t received your result? Check your spam folder or contact: equipe@inspiratanature.com',
    },
    featured: {
      back: 'Back',
      hero: { title: 'LIQUID SUNSHINE', subtitle: 'WHOLE PLANT INFUSED OILS', cta: 'DISCOVER OUR OILS' },
      intro: { title: 'LOCAL PLANT INFUSED BODY OILS', subtitle: 'Hydrate + Soften + Activate', quote: 'And when our body makes us feel it is time to act...' },
      title: 'Current Rituals', subtitle: 'Essentials',
      products: [
        { name: 'Vata Body Oil', price: '48.00 CAD', type: 'Grounding & Serenity' },
        { name: 'Face Ritual', price: '85.00 CAD', type: 'Natural Glow' },
        { name: 'Book: Nature & Ayurveda', price: '34.95 CAD', type: 'Daily Wisdom' },
      ],
    },
    shop: {
      title: 'Inspirata Ayurveda Shop', subtitle: 'Nature & Wellness',
      products: [
        { id: 1, title: 'The Soothing Vata', price: '48.00 CAD', type: 'Body Oil', image: ASSETS.productVata },
        { id: 2, title: 'The Refreshing Pitta', price: '48.00 CAD', type: 'Body Oil', image: ASSETS.productVata },
        { id: 3, title: 'The Stimulating Kapha', price: '48.00 CAD', type: 'Body Oil', image: ASSETS.productVata },
        { id: 4, title: 'Zen Nose', price: '28.00 CAD', type: 'Specific Care', image: ASSETS.productVata },
      ],
    },
    locations: {
      title: 'Our Partners',
      intro: 'Each partner has been carefully chosen for their heart connection and values.',
      regions: [
        { name: 'Eastern Townships', spots: [
          { name: 'Spa Eastman', address: '895 ch des Dilligences\nEastman, QC, J0E 1P0', tel: '1 800 665-5272', hours: 'Mon-Sun: 7am - 10pm' },
          { name: 'Caroline Cazes', address: '1074 chemin de la Montagne\nOrford, QC, J1X 6X9', tel: '819-578-7707', hours: 'By appointment only' },
        ]},
        { name: 'Quebec - Trois Rivières', spots: [
          { name: 'Monastère des Augustines', address: '77 rue des Remparts\nQuébec, QC, G1R 0C3', tel: '418 694-1639', hours: 'Mon-Sun: 7am - 9pm' },
        ]},
      ],
    },
    media: {
      title: 'Podcast & Media', subtitle: 'Explore our content', back: 'Back',
      sections: [
        { id: 'podcast', label: 'Podcast', icon: 'fa-microphone' },
        { id: 'tv', label: 'TV', icon: 'fa-tv' },
        { id: 'book', label: 'Books', icon: 'fa-book' },
        { id: 'blog', label: 'Blog', icon: 'fa-pen-nib' },
      ],
      details: {
        podcast: { title: 'Beyond Trends', subtitle: 'The Inspirata Podcast', spotifyUrl: 'https://open.spotify.com/embed/show/0cHEVMLF92tJxiO7MwyOKD?utm_source=generator', ctaLink: 'https://open.spotify.com/show/0cHEVMLF92tJxiO7MwyOKD', points: ['Deep conversations, far from ambient noise.', 'Practical keys inspired by living wisdom.', 'A voice to regain energy and clarity.'], newsletter: { title: 'Stay Connected', subtitle: '( outside social media )', desc: 'Receive every new Inspirata podcast episode directly by email.', button: 'Subscribe' }, cta: 'Listen to episodes', promo: 'Discover Essential Rituals' },
        tv: { title: 'TV Shows & Interviews', desc: 'Our founder in SANTÉ LA VIE for 3 seasons, invited to discuss Ayurveda.', videos: [{ id: 'v9uMfDmQ2YE', title: 'Santé! La Vie!' }, { id: 'fxzVTt5RfBw', title: 'Salut Bonjour' }, { id: '8t1BfEk_2do', title: 'François Lemay' }, { id: 'wtQ_MEgkrVE', title: 'Daniel Blouin' }, { id: 'ab-EEYQi7yM', title: 'France Gauthier' }, { id: 't3KNbXTyI5I', title: 'Diva Yoga - Interview' }, { id: '2KWQuUbhmsU', title: 'Diva Yoga - Ritual' }] },
        book: { title: 'Our Books', items: [
          { title: 'Nature & Ayurveda', fullTitle: 'Nature & Ayurveda Book', subtitle: 'Best seller x 5 in Francophonie', status: 'available', price: '34.99 CAD', reviews: '21 reviews', cover: 'https://storage.googleapis.com/inspirata/Livres/nature%20ayurveda%20front.jpg', shortDesc: 'If Ayurveda were a book, it would be named Nature & Ayurveda!', features: ['Vegan', 'Authentic Ingredients', 'Eco-friendly'], longDesc: 'A journey towards balance.', conclusion: 'The essential guide to a balanced life.', detailedReviews: [{ user: 'Marie-Claude', text: 'A revelation! Changed my daily routine.', rating: 5 }, { user: 'Sophie L.', text: 'Simple, accessible and beautiful.', rating: 5 }] },
          { title: 'Femininity & Ayurveda', fullTitle: 'Femininity & Ayurveda Book', subtitle: 'Best seller x 5 in Francophonie', status: 'available', price: '39.99 CAD', reviews: '25 reviews', cover: 'https://storage.googleapis.com/inspirata/Livres/feminite%20ayurveda%20front.jpg', shortDesc: 'If Ayurveda could express its link with the Sacred Feminine.', features: ['Vegan', 'Hormonal Support', 'Feminine Well-being'], longDesc: 'A gentle invitation to reconnect with your body.', conclusion: 'The ideal companion for every woman.', previewPages: ['https://storage.googleapis.com/inspirata/Livres/page%202%20fem.avif', 'https://storage.googleapis.com/inspirata/Livres/page%202.avif'], detailedReviews: [{ user: 'Julie P.', text: 'Essential for all women.', rating: 5 }] },
          { title: 'Wisdom to come', desc: 'Coming Soon', status: 'locked' },
        ]},
        blog: { title: 'The Blog', subtitle: 'Readings and Reflections' },
        default: { title: 'Coming Soon', items: [] },
      },
    },
    founder: {
      bio: { intro: 'In a world of constant acceleration, slowing down is essential.', p1: 'For more than 35 years, I have woven rituals rooted in Ayurveda, plants, breathing, and inner listening.', p2: 'This work does not follow trends.', highlight: 'Two of my books have been best-sellers.', expert: 'Emergency Nurse (10 years)', mission: 'I dedicate my life to the Art of Conscious Living.', outro: 'Welcome to a space to reconnect.' },
      stats: [{ value: '35+', label: 'Years of Experience', sub: 'Holistic Health' }, { value: '2', label: 'Francophonie', sub: 'Best-Sellers' }, { value: '3', label: 'Santé La Vie', sub: 'TV Seasons' }, { value: '10', label: 'Critical Care', sub: 'Years' }],
      story: { title: 'THE LOVE STORY', subtitle: 'BETWEEN KRYSTINE ST-LAURENT & AYURVEDA', p1: 'I have the immense privilege of living my dream life daily.', p2: 'Inspired by the history of the first nurses in America (the Augustinian sisters).', p3: 'I deeply believe our body is unique and made to regenerate.', p4: 'Imagine a vibrant, alive, conscious community.', p5: 'I wish to accompany you on this Ayurvedic path: a return to oneself.' },
      newsletter: { title: 'It\'s not a newsletter.', subtitle: 'It\'s a thread of wisdom.', intro: 'In a world that changes every second...', list: ['Sometimes: a meditation, a ritual', 'Sometimes: an excerpt from the next book', 'Sometimes: a simple reminder'], outro: 'For those who feel a call — even soft, even blurry.', formTitle: 'Stay Connected', cta: 'Join the thread' },
      footerBio: { title: 'WHO IS KRYSTINE ST-LAURENT?', text: 'Krystine St-Laurent is a best-selling author, international speaker, and recognized expert in Ayurveda.' },
      cta: 'Book Krystine',
    },
    booking: { title: 'Book Krystine for your event!', bio: 'Recognized expert in Ayurveda, holistic health, and aligned living.', program: 'Internationally trained, best-selling author, and sought-after speaker.', ritual: { title: 'If your body rewrote the agenda?', desc: 'Join us for 21 days of rituals, simple, 5 to 10 minutes a day!', cta: 'I join the movement', kajabiLink: 'https://kajabi.com/checkout-placeholder' } },
    evenements: {
      title: 'Events',
      subtitle: 'Meet Krystine in person',
      noEvents: 'No upcoming events at this time. Check back soon!',
      register: 'Register',
      inPerson: 'In Person',
      online: 'Online',
      past: 'Past Events',
      upcoming: 'Upcoming',
    },
    footer: { contact: 'Contact', newsletter: 'Newsletter', privacy: 'Privacy Policy', madeBy: 'Platform developed by' },
    origine: {
      hero: { title: 'Origin Experience', subtitle: 'The problem is not a lack of discipline. It is the loss of a reliable inner reference.', cta: 'Join the Workshop' },
      transition: 'Discover even more with Krystine',
      about: { title: 'Krystine St-Laurent', p1: '35 years traversing health environments before choosing herbalism, Ayurveda, and aromatherapy.', testimonials: [{ text: 'No one talks about these things like Krystine.', author: 'Annie' }, { text: 'This is the first time someone gives me the tools to listen to myself.', author: 'Françoise' }, { text: 'What I read in a hundred books without understanding, Krystine made obvious.', author: 'Marie' }] },
      timeline: { title: 'The Apothecary\'s Path', intro: 'A progressive 3-stage journey.', steps: [{ id: '01', title: 'Grounding (Earth)', duration: 'Weeks 1-4', desc: 'Installing the reference.', details: 'Sleep, nutrition, morning routines.' }, { id: '02', title: 'Alchemy (Fire)', duration: 'Weeks 5-8', desc: 'Digestive transformation.', details: 'Digestive fire (Agni) capacity.' }, { id: '03', title: 'Clarity (Ether)', duration: 'Weeks 9-12', desc: 'Embodying coherence.', details: 'When the noise settles, vision becomes clear.' }] },
      pricing: { title: 'Join the Circle', price: 'Founder Access', features: ['Full access to 3 Modules', 'Printable Workbooks', 'Monthly Q&A Sessions', 'Private Community'], cta: 'Start the Experience', guarantee: { badge: '30 Day Guarantee', title: 'Light Heart Guarantee', text: 'If you don\'t feel the promised grounding, we will refund you in full.' } },
    },
  },
} as const;

export type ContentLang = keyof typeof CONTENT;
